// ════════════════════════════════════════════════════════════════════════
//  Services/Interfaces/IAdminEncounterService.cs
//  Admin encounter access — view all, filter by status, download PDF.
//  Admin cannot edit — approved encounters are permanently locked.
// ════════════════════════════════════════════════════════════════════════

using UL_Optometry.Models.Common;
using UL_Optometry.Models;

namespace UL_Optometry.Services.Interfaces;

public interface IAdminEncounterService
{
    // ── Lists ─────────────────────────────────────────────────────────
    /// <summary>
    /// All encounters across all students.
    /// Pass a status string to filter (e.g. "Approved").
    /// Pass null for all statuses.
    /// Results include joined student name, clinic, date.
    /// </summary>
    Task<ApiResult<List<Encounter>>> GetAllEncountersAsync(string? status = null);

    /// <summary>Single encounter by ID with all sections and attachments.</summary>
    Task<ApiResult<Encounter>> GetEncounterByIdAsync(Guid encounterId);

    // ── PDF ───────────────────────────────────────────────────────────
    /// <summary>
    /// Get a signed URL to download a signed-off encounter as PDF.
    /// Only available for status = "Approved" encounters.
    /// PDF generated by a Supabase Edge Function.
    /// </summary>
    Task<ApiResult<string>> GetPdfUrlAsync(Guid encounterId);
}
